name       : mojave-gtk-theme
version    : '20221021'
release    : 9
source     :
    - https://github.com/vinceliuice/Mojave-gtk-theme/archive/refs/tags/2022-10-21.tar.gz : 5bf769b7c5fd1806b7d814d50ce44acabc6c84774540e3e562d6d48df352cd60
homepage   : https://github.com/vinceliuice/Mojave-gtk-theme
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - alt : desktop.theme
summary    : Mojave is a Mac OS X Mojave like theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell
description: |
    Mojave is a Mac OS X like theme for GTK 2, GTK 3, and GTK 4, as well as the Budgie, GNOME Shell, and MATE desktop environments.
patterns   :
    - alt : /usr/share/themes/*alt*
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
    - alt :
        - mojave-gtk-theme
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{COPYING,cinnamon}
