name       : mojave-gtk-theme
version    : '20200220'
release    : 2
source     :
    - https://github.com/vinceliuice/Mojave-gtk-theme/archive/2020-02-20.tar.gz : c3ccb2eaa7defd85f511431c4cee8f93f57506044cbc39a7edfe2eff36dee04e
homepage   : https://github.com/vinceliuice/Mojave-gtk-theme
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - alt : desktop.theme
summary    : Mojave is a macos Mojave like theme for GTK 3, GTK 2 and Gnome-Shell
description: |
    Mojave is a Mac OSX like theme for GTK 3, GTK 2 and Gnome-Shell which supports GTK 3 and GTK 2 based desktop environments like Gnome, Budgie and Mate.
patterns   :
    - alt : /usr/share/themes/*alt*
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{COPYING,cinnamon}
