name       : mojave-gtk-theme
version    : '20220607'
release    : 8
source     :
    - https://github.com/vinceliuice/Mojave-gtk-theme/archive/refs/tags/2022-06-07.tar.gz : e13d0f4f13ea27a948f8ae444b38ae7147e96a41d499e81a8cf57187bfd05a9a
homepage   : https://github.com/vinceliuice/Mojave-gtk-theme
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - alt : desktop.theme
summary    : Mojave is a Mac OS X Mojave like theme for GTK 2, GTK 3, GTK 4 and Gnome-Shell
description: |
    Mojave is a Mac OS X like theme for GTK 2, GTK 3, and GTK 4, as well as the Budgie, GNOME Shell, and MATE desktop environments.
patterns   :
    - alt : /usr/share/themes/*alt*
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
    - alt :
        - mojave-gtk-theme
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{COPYING,cinnamon}
